<SparatorHorizon>:
    size_hint: 1, None
    height: dp(1)
    canvas:
        Color:
            rgba:root.color
        Line:
            points:self.x+self.padding,self.y,self.right-self.padding,self.y
<SparatorVertical>:
    size_hint: None,1
    width:dp(1)
    canvas:
        Color:
            rgba:root.color
        Line:
            points:self.x,self.y+self.padding,self.x,self.top-self.padding

                    